image: node:16

stages:
  - lint
  - release

lint_test:
  stage: lint
  script:
    - npm install
    - npm run lint
    - npm run test
  tags:
    - docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null

release:
  stage: release
  script:
    - npm i
    - npm run test && npm run lint
    - npm config set -- //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${GITLAB_TOKEN}
    - npm config set @${CI_PROJECT_ROOT_NAMESPACE}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm publish
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG != null
